#!/usr/bin/python

import time

from gevent import monkey; monkey.patch_all()
import gevent.wsgi
import gevent.server

import IRCConnection
import HTTPConnection

from LogEntry import *

# requires: python gevent

def log(s):
    print "***", s

def now():
    t = time.gmtime()[0:6]
    return t

irc_server = gevent.server.StreamServer(('', 6667), IRCConnection.IRCConnection)
irc_server.start()

http_server = gevent.wsgi.WSGIServer(('', 5000), HTTPConnection.HTTPConnection)
http_server.serve_forever()

